### ISSUE TITLE
Panics in API command

### ISSUE THREAD

**Issue by jperkin** [42wim/mm-go-irckit#9]
The commit 816784be67d0241f8266ac19eaa9c7c2fc766c8b disables the check which ensured that a command has enough parameters. This results in panics when a user requests an `api` command with a single argument (for example `api help`):

```
panic: runtime error: slice bounds out of range
```

The offending code is this block:

```
        if strings.ToLower(args[0]) == "get" {
                r, err = u.mc.Client.DoApiGet(args[1], "", "")
        } else {
                r, err = u.mc.Client.DoApiPost(args[1], strings.Join(args[2:], " "))
        }
```

The fix is obvious, but I don't know enough about the intent of the `api` command and why `get` is handled specially to be able to offer a suitable patch.

**Comment by 42wim** [comment]
Hi thanks for reporting and debugging, it's a remnant of testing. 
I'm removing it.
